export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION'
export const SET_SELECTED_BUS_STATION = 'SET_SELECTED_BUS_STATION'

export const GET_ALL_ROUTES = 'GET_ALL_ROUTES'
export const GET_FORWARD_ROUTE_STATIONS = 'GET_FORWARD_ROUTE_STATIONS'
export const GET_BACKWARD_ROUTE_STATIONS = 'GET_BACKWARD_ROUTE_STATIONS'
export const SET_DIRECTION = 'SET_DIRECTION'
export const RESET_ROUTE_STATION = 'RESET_ROUTE_STATION'
export const SET_FOUND_ROUTE = 'SET_FOUND_ROUTE'
export const SET_SUGGESTED_ROUTE_LIST = 'SET_SUGGESTED_ROUTE_LIST'
export const SET_SELECTED_SUGGESTED_ROUTE = 'SET_SELECTED_SUGGESTED_ROUTE'
export const SET_MAXIMUM_NUMBER_OF_ROUTE = 'SET_MAXIMUM_NUMBER_OF_ROUTE'

export const BUS_STATUS_CHANGED = 'BUS_STATUS_CHANGED'
export const LOCATION_CHANGED = 'LOCATION_CHANGED'
export const GET_ACTIVE_BUSES = 'GET_ACTIVE_BUSES'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const LOGOUT = 'LOGOUT'

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE'

export const EDIT_PROFILE_CLICK = 'EDIT_PROFILE_CLICK'

export const CLEAR_ERROR = 'CLEAR_ERROR'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE'

export const SEND_FRIEND_INVITE_REQUEST = 'SEND_FRIEND_INVITE_REQUEST'
export const SEND_FRIEND_INVITE_SUCCESS = 'SEND_FRIEND_INVITE_REQUEST'
export const SEND_FRIEND_INVITE_FAILUTE = 'SEND_FRIEND_INVITE_FAILUTE'

export const GET_FRIEND_REQUEST = 'GET_FRIEND_REQUEST'
export const GET_FRIEND_SUCCESS = 'GET_FRIEND_SUCCESS'
export const GET_FRIEND_FAILURE = 'GET_FRIEND_FAILURE'

export const GET_FRIEND_INVITE_REQUEST = 'GET_FRIEND_INVITE_REQUEST'
export const GET_FRIEND_INVITE_SUCCESS = 'GET_FRIEND_INVITE_SUCCESS'
export const GET_FRIEND_INVITE_FAILUTE = 'GET_FRIEND_INVITE_FAILUTE'

export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST'
export const REJECT_FRIEND_REQUEST = 'REJECT_FRIEND_REQUEST'
export const ACCEPT_FRIEND_SUCCESS = 'ACCEPT_FRIEND_SUCCESS'
export const REJECT_FRIEND_SUCCESS = 'REJECT_FRIEND_SUCCESS'

export const GET_MY_TICKET_REQUEST = 'GET_MY_TICKET_REQUEST'
export const GET_MY_TICKET_SUCCESS = 'GET_MY_TICKET_SUCCESS'
export const GET_MY_TICKET_FAILURE = 'GET_MY_TICKET_FAILURE'
export const QR_CODE = 'QR_CODE'

export const SET_PROGRESS = 'SET_PROGRESS'

export const GET_FRIEND_CHECK_IN_REQUEST = 'GET_FRIEND_CHECK_IN_REQUEST'
export const GET_FRIEND_CHECK_IN_SUCCESS = 'GET_FRIEND_CHECK_IN_SUCCESS'
export const GET_FRIEND_CHECK_IN_FAILURE = 'GET_FRIEND_CHECK_IN_FAILURE'

export const GET_NOTI_REQUEST = 'GET_NOTI_REQUEST'
export const GET_NOTI_SUCCESS = 'GET_NOTI_SUCCESS'
export const GET_NOTI_FAILURE = 'GET_NOTI_FAILURE'

export const ACTIVE_FRIEND_REQUEST = 'ACTIVE_FRIEND_REQUEST'
export const ACTIVE_FRIEND_SUCCESS = 'ACTIVE_FRIEND_SUCCESS'
export const ACTIVE_FRIEND_FAILURE = 'ACTIVE_FRIEND_FAILURE'

export const FREEZE_FRIEND_REQUEST = 'FREEZE_FRIEND_REQUEST'
export const FREEZE_FRIEND_SUCCESS = 'FREEZE_FRIEND_SUCCESS'
export const FREEZE_FRIEND_FAILURE = 'FREEZE_FRIEND_FAILURE'
