export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION'
export const SET_SELECTED_BUS_STATION = 'SET_SELECTED_BUS_STATION'

export const GET_ALL_ROUTES = 'GET_ALL_ROUTES'
export const GET_FORWARD_ROUTE_STATIONS = 'GET_FORWARD_ROUTE_STATIONS'
export const GET_BACKWARD_ROUTE_STATIONS = 'GET_BACKWARD_ROUTE_STATIONS'
export const SET_DIRECTION = 'SET_DIRECTION'
export const RESET_ROUTE_STATION = 'RESET_ROUTE_STATION'
export const SET_FOUND_ROUTE = 'SET_FOUND_ROUTE'
export const SET_SUGGESTED_ROUTE_LIST = 'SET_SUGGESTED_ROUTE_LIST'
export const SET_SELECTED_SUGGESTED_ROUTE = 'SET_SELECTED_SUGGESTED_ROUTE'
export const SET_MAXIMUM_NUMBER_OF_ROUTE = 'SET_MAXIMUM_NUMBER_OF_ROUTE'

export const BUS_STATUS_CHANGED = 'BUS_STATUS_CHANGED'
export const LOCATION_CHANGED = 'LOCATION_CHANGED'
export const GET_ACTIVE_BUSES = 'GET_ACTIVE_BUSES'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const LOGOUT = 'LOGOUT'
